default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mr_crawler_development

test:
  <<: *default
  database: mr_crawler_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
